[theme]
primaryColor = "#0052CC"  # RBC Blue
backgroundColor = "#171723"  # Black
secondaryBackgroundColor = "#F8F9FA"  # Light Gray
textColor = "#ffffff"  # White
font = "sans serif"
base="dark"

[server]
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = false

[runner]
fastRerenderThreshold = 1000

[client]
showErrorDetails = false 
