[theme]
base="dark"
primaryColor="#0052cc"
font = "sans serif"
base="dark"


[server]
enableXsrfProtection = true
enableCORS = false
enableWebsocketCompression = false

[runner]
fastRerenderThreshold = 1000

[client]
showErrorDetails = false 
